import React, { useState, useRef, useEffect } from "react";

const BASIS_PRESETS = [
  "Cost of Living & Economy",
  "Safety, Healthcare & Wellness",
  "Culture, Lifestyle & Food",
  "Business & Tech Opportunities",
  "Tourism & Sightseeing",
  "Weather, Climate & Geography",
  "Visas & Immigration Friendliness"
];

// Custom Lightweight Markdown Parser
const renderMarkdownBeautifully = (text) => {
  if (!text) return null;
  return text.split('\n').map((line, i) => {
    if (line.startsWith('### ')) return <h3 key={i} className="text-[1.1rem] font-bold text-sky-300 mt-6 mb-2">{line.replace('### ', '')}</h3>;
    if (line.startsWith('## ')) return <h2 key={i} className="text-[1.3rem] font-extrabold text-white mt-8 mb-3 border-b border-slate-700 pb-2">{line.replace('## ', '')}</h2>;
    if (line.startsWith('# ')) return <h1 key={i} className="text-[1.6rem] font-black text-sky-400 mt-8 mb-4">{line.replace('# ', '')}</h1>;
    
    const parseBold = (str) => {
      return str.split(/(\*\*.*?\*\*)/g).map((part, j) => 
        part.startsWith('**') && part.endsWith('**') ? <strong key={j} className="text-white font-bold tracking-wide">{part.slice(2, -2)}</strong> : part
      );
    };

    if (line.trim().startsWith('* ') || line.trim().startsWith('- ')) {
      const content = line.trim().substring(2);
      return <li key={i} className="ml-6 list-disc mb-2 text-slate-300 pl-2 marker:text-sky-500">{parseBold(content)}</li>;
    }
    
    if (!line.trim()) return <div key={i} className="h-2"></div>;
    return <p key={i} className="mb-4 text-slate-300 leading-[1.7] text-[1rem]">{parseBold(line)}</p>;
  });
};

export default function CompareCanvasOverlay({ state, dispatch, handleCloseCompare, fetchComparison }) {
  const [showBasisDrop, setShowBasisDrop] = useState(false);
  const basisRef = useRef(null);
  const chatEndRef = useRef(null);

  // Local state for the compare doubts
  const [doubtsHistory, setDoubtsHistory] = useState([]);
  const [doubtsText, setDoubtsText] = useState("");
  const [showDoubtsInput, setShowDoubtsInput] = useState(false);
  const [isDoubtLoading, setIsDoubtLoading] = useState(false);

  // Extract the comparison data generated by the Sidebar's fetch
  const { countryA, countryB, listA, listB, purpose, basis } = state.compareData || {};

  // Auto-scroll chat
  useEffect(() => {
    if (chatEndRef.current) {
      chatEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [doubtsHistory]);

  // Click outside dropdown
  useEffect(() => {
    const handleClick = (e) => {
      if (basisRef.current && !basisRef.current.contains(e.target)) setShowBasisDrop(false);
    };
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  const sendCompareDoubt = async () => {
    if (!doubtsText.trim() || isDoubtLoading) return;
    
    const currentDoubt = doubtsText;
    setDoubtsText("");
    setDoubtsHistory(prev => [...prev, { sender: 'user', text: currentDoubt }]);
    setIsDoubtLoading(true);
    
    try {
      const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";
      const headers = { "Content-Type": "application/json" };
      if (state.token) headers["Authorization"] = `Bearer ${state.token}`;

      const response = await fetch(`${API_URL}/api/compare-doubt`, {
        method: "POST",
        headers: headers,
        body: JSON.stringify({
          countryA, countryB, purpose, basis, doubt: currentDoubt
        })
      });

      if (!response.ok) throw new Error("Network response was not ok");

      const reader = response.body.getReader();
      const decoder = new TextDecoder("utf-8");
      let fullText = "";
      let buffer = "";

      // Add a temporary empty AI message that we will stream into
      setDoubtsHistory(prev => [...prev, { sender: 'ai', text: "" }]);

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop();

        for (const line of lines) {
          if (!line.trim()) continue;
          try {
            const parsed = JSON.parse(line);
            if (parsed.type === "chunk" || parsed.type === "error") {
              fullText += parsed.text;
              // Update the last message in real-time
              setDoubtsHistory(prev => {
                const newHistory = [...prev];
                newHistory[newHistory.length - 1].text = fullText;
                return newHistory;
              });
            }
          } catch (e) {}
        }
      }
    } catch (error) {
      console.error("Doubt Error:", error);
      setDoubtsHistory(prev => [...prev, { sender: 'ai', text: "❌ Connection to Intelligence Core lost." }]);
    } finally {
      setIsDoubtLoading(false);
    }
  };

  return (
    <div className={`
      flex flex-col min-h-0 bg-[#0f172a]/70 backdrop-blur-2xl shadow-[0_-10px_30px_rgba(0,0,0,0.5)] border-t border-white/10 relative z-20
      transition-all duration-500 ease-[cubic-bezier(0.4,0,0.2,1)]
      ${state.isCompareActive 
        ? "flex-1 opacity-100 translate-y-0 border-t-2 border-sky-500" 
        : "h-0 flex-none opacity-0 translate-y-20 overflow-hidden border-t-0 border-r-transparent"}
    `}>
      
      <style>{`
        @keyframes slideDownFade { 0% { opacity: 0; transform: translateY(-15px); } 100% { opacity: 1; transform: translateY(0); } }
        .animate-reveal { animation: slideDownFade 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards; }
        .custom-scrollbar::-webkit-scrollbar { width: 8px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: #090d16; border-radius: 8px; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: #334155; border-radius: 8px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: #475569; }
      `}</style>

      {/* Header Bar */}
      <div className="flex-none flex justify-between bg-slate-800 border-b border-slate-700 py-3 px-6">
        <h2 className="text-white font-black tracking-widest uppercase flex items-center gap-3">
          <span className="text-sky-400">{countryA || "Country A"}</span>
          <span className="text-slate-500 text-sm">VS</span>
          <span className="text-emerald-400">{countryB || "Country B"}</span>
        </h2>
        
        {/* Window Controls */}
        <div className="flex items-center gap-3">
          <button 
            className="text-slate-400 hover:bg-sky-500 hover:text-white px-2 py-1 rounded-md text-[1.2rem] transition-all duration-300 cursor-pointer" 
            title={state.isCanvasExpanded ? "Restore Down" : "Maximize"}
            onClick={() => dispatch({ type: "TOGGLE_EXPAND" })}
          >
            {state.isCanvasExpanded ? "🗗" : "🗖"}
          </button>
          <button 
            className="text-slate-400 hover:bg-red-500 hover:text-white px-2 py-1 rounded-md text-[1.2rem] transition-all duration-300 cursor-pointer" 
            title="Close Comparison"
            onClick={handleCloseCompare} 
          >
            ✖
          </button>
        </div>
      </div>

      {/* Main Body */}
      <div className="flex-1 flex flex-col min-h-0 p-6 relative">
        
        {/* Context Control Bar */}
        <div className="flex-none flex items-center gap-4 mb-6 relative" ref={basisRef}>
          <div className="px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg text-slate-400 text-sm font-semibold flex items-center gap-2">
            Context: <span className="text-violet-400">{purpose || "General"}</span>
          </div>
          
          <div className="flex flex-1 max-w-[400px]">
            <input 
              type="text" className="flex-1 p-3 bg-slate-900/60 border border-slate-700 border-r-0 rounded-l-lg text-slate-50 outline-none focus:border-sky-500 text-sm" 
              placeholder="Update Basis of Comparison..." 
              value={state.compareData?.basis || ""} 
              onChange={(e) => dispatch({ type: "SET_COMPARE_DATA", payload: { ...state.compareData, basis: e.target.value } })} 
            />
            <button className="px-3 bg-slate-900/60 border border-slate-700 rounded-r-lg text-slate-500 hover:text-sky-500 cursor-pointer" onClick={() => setShowBasisDrop(!showBasisDrop)}>▾</button>
          </div>

          <button 
            className="bg-sky-600 hover:bg-sky-500 text-white py-2.5 px-8 rounded-xl text-[1rem] font-bold tracking-wider uppercase transition-all shadow-[0_0_15px_rgba(14,165,233,0.3)] cursor-pointer disabled:opacity-50" 
            onClick={() => fetchComparison()} 
            disabled={state.isLoading}
          >
            {state.isLoading ? "Analyzing..." : "Re-Compare"}
          </button>

          {showBasisDrop && (
            <div className="absolute top-full left-[200px] w-[400px] mt-1 bg-[#0f172a] border border-slate-700 rounded-lg z-50 shadow-xl overflow-hidden">
              {BASIS_PRESETS.map(preset => (
                <div key={preset} className="p-3 text-[0.9rem] text-slate-400 cursor-pointer hover:bg-sky-500 hover:text-white transition-colors" 
                     onClick={() => { dispatch({ type: "SET_COMPARE_DATA", payload: { ...state.compareData, basis: preset } }); setShowBasisDrop(false); }}>
                  {preset}
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Scrollable Canvas Area (Holds Split Screen + Chat) */}
        <div className="flex-1 overflow-y-auto bg-gray-400/20 backdrop-blur-lg border border-white/10 rounded-lg px-2 py-6 shadow-lg custom-scrollbar relative">
          
          {state.isLoading && (!listA || !listB) ? (
            <div className="flex items-center justify-center h-full text-sky-400 animate-pulse font-semibold text-lg tracking-widest">
              [ RUNNING COMPARATIVE ANALYSIS... ]
            </div>
          ) : (
            <div className="max-w-full mx-auto w-full animate-reveal flex flex-col">
              
              {/* --- NEW PHOTO-FRAME SPLIT SCREEN DESIGN --- */}
              {listA && listB && (
                <div className="flex w-full bg-slate-900/30 backdrop-blur-xl rounded-[20px] border-[1px] border-white/10 shadow-[0_8px_32px_rgba(0,0,0,0.3)] overflow-hidden mb-12 relative">
                  
                  {/* Country A Left Frame */}
                  <div className="flex-1 flex flex-col bg-slate-900/60 shadow-[inset_0_0_40px_rgba(0,0,0,0.4)] relative">
                    <div className="bg-slate-950 p-6 border-b-[6px] border-sky-600/60 shadow-md">
                      <h2 className="text-3xl lg:text-4xl font-black text-sky-400 text-center tracking-widest uppercase">{countryA}</h2>
                    </div>
                    <div className="p-10 flex-1 overflow-y-auto custom-scrollbar text-slate-300 leading-relaxed text-[1.05rem]">
                      {listA.map((point, idx) => (
                        <div key={idx} className="mb-4">
                          {renderMarkdownBeautifully(point)}
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* THICK DIVIDER POLE */}
                  <div className="w-8 bg-gradient-to-b from-gray-300/20 via-gray-400/20 to-gray-300/20 flex flex-col items-center justify-center backdrop-blur-md shadow-[0_-4px_8px_rgba(0,0,0,0.3),0_4px_8px_rgba(0,0,0,0.3)] relative z-10">
                    <div className="absolute w-12 h-12 bg-gray-300/20 border border-white/20 rounded-full flex items-center justify-center text-gray-200 font-black text-[0.7rem] backdrop-blur-md shadow-lg">
                      VS
                    </div>
                  </div>

                  {/* Country B Right Frame */}
                  <div className="flex-1 flex flex-col bg-slate-900/60 shadow-[inset_0_0_40px_rgba(0,0,0,0.4)] relative">
                    <div className="bg-slate-950 p-6 border-b-[6px] border-emerald-600/60 shadow-md">
                      <h2 className="text-3xl lg:text-4xl font-black text-emerald-400 text-center tracking-widest uppercase">{countryB}</h2>
                    </div>
                    <div className="p-10 flex-1 overflow-y-auto custom-scrollbar text-slate-300 leading-relaxed text-[1.05rem]">
                      {listB.map((point, idx) => (
                        <div key={idx} className="mb-4">
                          {renderMarkdownBeautifully(point)}
                        </div>
                      ))}
                    </div>
                  </div>

                </div>
              )}
              
              {/* --- DOUBTS CHAT HISTORY (Unchanged layout) --- */}
              {doubtsHistory.length > 0 && (
                <div className="pt-8 border-t border-t-[3px] border-sky-500/80 max-w-6xl mx-auto w-full">
                  {doubtsHistory.map((msg, idx) => (
                    <div key={idx} className={`mb-6 flex ${msg.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
                      <div className={`
                        max-w-[80%] p-5 rounded-2xl text-[1.05rem] leading-[1.7] shadow-md
                        ${msg.sender === 'user' 
                          ? 'bg-sky-600/20 border border-sky-500/30 text-sky-100 rounded-tr-sm' 
                          : 'bg-slate-800 border border-blue-700 text-slate-200 rounded-tl-sm'}
                      `}>
                        {msg.sender === 'ai' ? renderMarkdownBeautifully(msg.text) : msg.text}
                      </div>
                    </div>
                  ))}
                  <div ref={chatEndRef} className="h-4"></div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* --- FLOATING DOUBT BUTTON & INPUT --- */}
        <div className="absolute bottom-10 right-10 z-30 flex items-center justify-end h-[50px]">
          <button 
            className={`
              bg-sky-600 hover:bg-sky-500 text-white rounded-[30px] font-bold text-[1.1rem] 
              shadow-[0_4px_15px_rgba(14,165,233,0.5)] cursor-pointer transition-all duration-300
              ${showDoubtsInput ? 'w-0 h-0 opacity-0 overflow-hidden p-0' : 'px-6 py-3 hover:-translate-y-1 w-auto h-auto opacity-100'}
            `}
            onClick={() => setShowDoubtsInput(true)}
          >
            Doubts?
          </button>

          <div className={`
            flex gap-2 bg-slate-800 rounded-[30px] border border-sky-500 shadow-[0_10px_25px_rgba(0,0,0,0.6)] items-center
            transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] overflow-hidden
            ${showDoubtsInput ? 'w-[450px] p-2 opacity-100' : 'w-0 p-0 opacity-0 border-none'}
          `}>
            <input 
              type="text" placeholder="Ask AI about this comparison..." 
              autoFocus={showDoubtsInput}
              className="bg-transparent border-none text-white px-4 outline-none flex-1 min-w-0"
              value={doubtsText} 
              onChange={(e) => setDoubtsText(e.target.value)} 
              onKeyDown={(e) => e.key === 'Enter' && sendCompareDoubt()}
            />
            <button 
              className="bg-sky-500 hover:bg-sky-400 text-white px-5 py-1.5 rounded-[20px] font-semibold transition-colors cursor-pointer disabled:opacity-50 flex-none"
              onClick={sendCompareDoubt}
              disabled={isDoubtLoading}
            >
              Send
            </button>
            <button 
              className="text-slate-400 hover:bg-red-500 hover:text-white px-2 py-1 rounded-full text-[1.2rem] transition-all duration-300 cursor-pointer flex-none" 
              onClick={() => setShowDoubtsInput(false)}
            >
              ✖
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}